FROM ghcr.io/cross-rs/x86_64-unknown-linux-musl:main

RUN apt-get update && \
apt-get --assume-yes install \
unzip

ENV PROTOBUF_VERSION=33.5
RUN curl -L -o protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip && \
    unzip protoc.zip -d protoc/ && \
    cp -r protoc/include/. /usr/include/ && \
    cp -r protoc/bin/. /usr/bin/ && \
    ldconfig

ENV MUSL_PREFIX=x86_64-linux-musl
ENV SQLITE_VERSION=3490100

RUN echo "Building SQLite" && \
  cd /tmp && \
  curl -fLO "https://sqlite.org/2025/sqlite-autoconf-$SQLITE_VERSION.tar.gz" && \
  tar xvzf "sqlite-autoconf-$SQLITE_VERSION.tar.gz" && cd "sqlite-autoconf-$SQLITE_VERSION" && \
  env CC=$MUSL_PREFIX-gcc ./configure --enable-static --prefix=/usr/local/$MUSL_PREFIX-target && \
  make && make install && \
  rm -r /tmp/*

ENV PKG_CONFIG_PATH=/usr/local/$MUSL_PREFIX-target/lib/pkgconfig
