// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/device_config_store.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceConfigStore struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enabled uplink channel indices in the channel mask.
	// (missing channels are disabled)
	EnabledUplinkChannelIndices []uint32 `protobuf:"varint,1,rep,packed,name=enabled_uplink_channel_indices,json=enabledUplinkChannelIndices,proto3" json:"enabled_uplink_channel_indices,omitempty"`
	// Data-rate.
	Dr *uint32 `protobuf:"varint,2,opt,name=dr,proto3,oneof" json:"dr,omitempty"`
	// Transmission power index.
	TxPowerIndex *uint32 `protobuf:"varint,3,opt,name=tx_power_index,json=txPowerIndex,proto3,oneof" json:"tx_power_index,omitempty"`
	// Number of transmissions.
	NbTrans *uint32 `protobuf:"varint,4,opt,name=nb_trans,json=nbTrans,proto3,oneof" json:"nb_trans,omitempty"`
	// Maximum duty-cycle.
	MaxDutyCycle  *uint32 `protobuf:"varint,5,opt,name=max_duty_cycle,json=maxDutyCycle,proto3,oneof" json:"max_duty_cycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceConfigStore) Reset() {
	*x = DeviceConfigStore{}
	mi := &file_api_device_config_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConfigStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConfigStore) ProtoMessage() {}

func (x *DeviceConfigStore) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceConfigStore.ProtoReflect.Descriptor instead.
func (*DeviceConfigStore) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceConfigStore) GetEnabledUplinkChannelIndices() []uint32 {
	if x != nil {
		return x.EnabledUplinkChannelIndices
	}
	return nil
}

func (x *DeviceConfigStore) GetDr() uint32 {
	if x != nil && x.Dr != nil {
		return *x.Dr
	}
	return 0
}

func (x *DeviceConfigStore) GetTxPowerIndex() uint32 {
	if x != nil && x.TxPowerIndex != nil {
		return *x.TxPowerIndex
	}
	return 0
}

func (x *DeviceConfigStore) GetNbTrans() uint32 {
	if x != nil && x.NbTrans != nil {
		return *x.NbTrans
	}
	return 0
}

func (x *DeviceConfigStore) GetMaxDutyCycle() uint32 {
	if x != nil && x.MaxDutyCycle != nil {
		return *x.MaxDutyCycle
	}
	return 0
}

type DeviceConfigStoreListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (EUI64).
	DevEui string `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceConfigStoreListItem) Reset() {
	*x = DeviceConfigStoreListItem{}
	mi := &file_api_device_config_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConfigStoreListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConfigStoreListItem) ProtoMessage() {}

func (x *DeviceConfigStoreListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceConfigStoreListItem.ProtoReflect.Descriptor instead.
func (*DeviceConfigStoreListItem) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceConfigStoreListItem) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

func (x *DeviceConfigStoreListItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DeviceConfigStoreListItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeviceUplinkChannel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Frequency Hz.
	Frequency uint32 `protobuf:"varint,1,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// Available data-rates.
	DataRates []uint32 `protobuf:"varint,2,rep,packed,name=data_rates,json=dataRates,proto3" json:"data_rates,omitempty"`
	// Whether this channel is enabled on the device.
	Enabled bool `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Whether this channel is not among regional defaults.
	UserDefined   bool `protobuf:"varint,5,opt,name=user_defined,json=userDefined,proto3" json:"user_defined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceUplinkChannel) Reset() {
	*x = DeviceUplinkChannel{}
	mi := &file_api_device_config_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceUplinkChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceUplinkChannel) ProtoMessage() {}

func (x *DeviceUplinkChannel) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceUplinkChannel.ProtoReflect.Descriptor instead.
func (*DeviceUplinkChannel) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceUplinkChannel) GetFrequency() uint32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *DeviceUplinkChannel) GetDataRates() []uint32 {
	if x != nil {
		return x.DataRates
	}
	return nil
}

func (x *DeviceUplinkChannel) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DeviceUplinkChannel) GetUserDefined() bool {
	if x != nil {
		return x.UserDefined
	}
	return false
}

type SetDeviceConfigStoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (EUI64).
	DevEui string `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Object to set.
	DeviceConfigStore *DeviceConfigStore `protobuf:"bytes,2,opt,name=device_config_store,json=deviceConfigStore,proto3" json:"device_config_store,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetDeviceConfigStoreRequest) Reset() {
	*x = SetDeviceConfigStoreRequest{}
	mi := &file_api_device_config_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceConfigStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceConfigStoreRequest) ProtoMessage() {}

func (x *SetDeviceConfigStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceConfigStoreRequest.ProtoReflect.Descriptor instead.
func (*SetDeviceConfigStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{3}
}

func (x *SetDeviceConfigStoreRequest) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

func (x *SetDeviceConfigStoreRequest) GetDeviceConfigStore() *DeviceConfigStore {
	if x != nil {
		return x.DeviceConfigStore
	}
	return nil
}

type GetDeviceConfigStoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (EUI64).
	DevEui        string `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceConfigStoreRequest) Reset() {
	*x = GetDeviceConfigStoreRequest{}
	mi := &file_api_device_config_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceConfigStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceConfigStoreRequest) ProtoMessage() {}

func (x *GetDeviceConfigStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceConfigStoreRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceConfigStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeviceConfigStoreRequest) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

type GetDeviceConfigStoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device configuration store object.
	DeviceConfigStore *DeviceConfigStore `protobuf:"bytes,1,opt,name=device_config_store,json=deviceConfigStore,proto3" json:"device_config_store,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceConfigStoreResponse) Reset() {
	*x = GetDeviceConfigStoreResponse{}
	mi := &file_api_device_config_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceConfigStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceConfigStoreResponse) ProtoMessage() {}

func (x *GetDeviceConfigStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceConfigStoreResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceConfigStoreResponse) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeviceConfigStoreResponse) GetDeviceConfigStore() *DeviceConfigStore {
	if x != nil {
		return x.DeviceConfigStore
	}
	return nil
}

func (x *GetDeviceConfigStoreResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetDeviceConfigStoreResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeleteDeviceConfigStoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (EUI64).
	DevEui        string `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceConfigStoreRequest) Reset() {
	*x = DeleteDeviceConfigStoreRequest{}
	mi := &file_api_device_config_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceConfigStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceConfigStoreRequest) ProtoMessage() {}

func (x *DeleteDeviceConfigStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceConfigStoreRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeviceConfigStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDeviceConfigStoreRequest) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

type ListDeviceConfigStoresRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Max number of chmasks to return in the result-set.
	// If not set, it will be treated as 0, and the response will only return the total_count.
	Limit uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset uint32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Application ID (UUID) to filter devices on.
	ApplicationId string `protobuf:"bytes,3,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceConfigStoresRequest) Reset() {
	*x = ListDeviceConfigStoresRequest{}
	mi := &file_api_device_config_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceConfigStoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceConfigStoresRequest) ProtoMessage() {}

func (x *ListDeviceConfigStoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceConfigStoresRequest.ProtoReflect.Descriptor instead.
func (*ListDeviceConfigStoresRequest) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{7}
}

func (x *ListDeviceConfigStoresRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDeviceConfigStoresRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListDeviceConfigStoresRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type ListDeviceConfigStoresResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of configuration stores.
	TotalCount uint32 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Result-set.
	Result        []*DeviceConfigStoreListItem `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceConfigStoresResponse) Reset() {
	*x = ListDeviceConfigStoresResponse{}
	mi := &file_api_device_config_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceConfigStoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceConfigStoresResponse) ProtoMessage() {}

func (x *ListDeviceConfigStoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceConfigStoresResponse.ProtoReflect.Descriptor instead.
func (*ListDeviceConfigStoresResponse) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{8}
}

func (x *ListDeviceConfigStoresResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListDeviceConfigStoresResponse) GetResult() []*DeviceConfigStoreListItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetDeviceConfigAlignmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (EUI64).
	DevEui        string `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceConfigAlignmentRequest) Reset() {
	*x = GetDeviceConfigAlignmentRequest{}
	mi := &file_api_device_config_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceConfigAlignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceConfigAlignmentRequest) ProtoMessage() {}

func (x *GetDeviceConfigAlignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceConfigAlignmentRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceConfigAlignmentRequest) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{9}
}

func (x *GetDeviceConfigAlignmentRequest) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

type GetDeviceConfigAlignmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alignment of the mask of enabled uplink channels.
	EnabledUplinkChannelIndices *bool `protobuf:"varint,1,opt,name=enabled_uplink_channel_indices,json=enabledUplinkChannelIndices,proto3,oneof" json:"enabled_uplink_channel_indices,omitempty"`
	// Alignment of the data-rate.
	Dr *bool `protobuf:"varint,2,opt,name=dr,proto3,oneof" json:"dr,omitempty"`
	// Alignment of the transmission power index.
	TxPowerIndex *bool `protobuf:"varint,3,opt,name=tx_power_index,json=txPowerIndex,proto3,oneof" json:"tx_power_index,omitempty"`
	// Alignment of the number of transmissions.
	NbTrans *bool `protobuf:"varint,4,opt,name=nb_trans,json=nbTrans,proto3,oneof" json:"nb_trans,omitempty"`
	// Alignment of the maximum duty-cycle.
	MaxDutyCycle  *bool `protobuf:"varint,5,opt,name=max_duty_cycle,json=maxDutyCycle,proto3,oneof" json:"max_duty_cycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceConfigAlignmentResponse) Reset() {
	*x = GetDeviceConfigAlignmentResponse{}
	mi := &file_api_device_config_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceConfigAlignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceConfigAlignmentResponse) ProtoMessage() {}

func (x *GetDeviceConfigAlignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceConfigAlignmentResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceConfigAlignmentResponse) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{10}
}

func (x *GetDeviceConfigAlignmentResponse) GetEnabledUplinkChannelIndices() bool {
	if x != nil && x.EnabledUplinkChannelIndices != nil {
		return *x.EnabledUplinkChannelIndices
	}
	return false
}

func (x *GetDeviceConfigAlignmentResponse) GetDr() bool {
	if x != nil && x.Dr != nil {
		return *x.Dr
	}
	return false
}

func (x *GetDeviceConfigAlignmentResponse) GetTxPowerIndex() bool {
	if x != nil && x.TxPowerIndex != nil {
		return *x.TxPowerIndex
	}
	return false
}

func (x *GetDeviceConfigAlignmentResponse) GetNbTrans() bool {
	if x != nil && x.NbTrans != nil {
		return *x.NbTrans
	}
	return false
}

func (x *GetDeviceConfigAlignmentResponse) GetMaxDutyCycle() bool {
	if x != nil && x.MaxDutyCycle != nil {
		return *x.MaxDutyCycle
	}
	return false
}

type GetDeviceCurrentParamsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (EUI64).
	DevEui        string `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceCurrentParamsRequest) Reset() {
	*x = GetDeviceCurrentParamsRequest{}
	mi := &file_api_device_config_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceCurrentParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceCurrentParamsRequest) ProtoMessage() {}

func (x *GetDeviceCurrentParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceCurrentParamsRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceCurrentParamsRequest) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{11}
}

func (x *GetDeviceCurrentParamsRequest) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

type GetDeviceCurrentParamsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uplink channels currently available to the device.
	Channels map[uint32]*DeviceUplinkChannel `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Data-rate.
	Dr uint32 `protobuf:"varint,2,opt,name=dr,proto3" json:"dr,omitempty"`
	// Transmission power index.
	TxPowerIndex uint32 `protobuf:"varint,3,opt,name=tx_power_index,json=txPowerIndex,proto3" json:"tx_power_index,omitempty"`
	// Number of transmissions.
	NbTrans uint32 `protobuf:"varint,4,opt,name=nb_trans,json=nbTrans,proto3" json:"nb_trans,omitempty"`
	// Maximum duty-cycle.
	MaxDutyCycle  uint32 `protobuf:"varint,5,opt,name=max_duty_cycle,json=maxDutyCycle,proto3" json:"max_duty_cycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceCurrentParamsResponse) Reset() {
	*x = GetDeviceCurrentParamsResponse{}
	mi := &file_api_device_config_store_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceCurrentParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceCurrentParamsResponse) ProtoMessage() {}

func (x *GetDeviceCurrentParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceCurrentParamsResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceCurrentParamsResponse) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{12}
}

func (x *GetDeviceCurrentParamsResponse) GetChannels() map[uint32]*DeviceUplinkChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *GetDeviceCurrentParamsResponse) GetDr() uint32 {
	if x != nil {
		return x.Dr
	}
	return 0
}

func (x *GetDeviceCurrentParamsResponse) GetTxPowerIndex() uint32 {
	if x != nil {
		return x.TxPowerIndex
	}
	return 0
}

func (x *GetDeviceCurrentParamsResponse) GetNbTrans() uint32 {
	if x != nil {
		return x.NbTrans
	}
	return 0
}

func (x *GetDeviceCurrentParamsResponse) GetMaxDutyCycle() uint32 {
	if x != nil {
		return x.MaxDutyCycle
	}
	return 0
}

var File_api_device_config_store_proto protoreflect.FileDescriptor

const file_api_device_config_store_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/device_config_store.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9d\x02\n" +
	"\x11DeviceConfigStore\x12C\n" +
	"\x1eenabled_uplink_channel_indices\x18\x01 \x03(\rR\x1benabledUplinkChannelIndices\x12\x13\n" +
	"\x02dr\x18\x02 \x01(\rH\x00R\x02dr\x88\x01\x01\x12)\n" +
	"\x0etx_power_index\x18\x03 \x01(\rH\x01R\ftxPowerIndex\x88\x01\x01\x12\x1e\n" +
	"\bnb_trans\x18\x04 \x01(\rH\x02R\anbTrans\x88\x01\x01\x12)\n" +
	"\x0emax_duty_cycle\x18\x05 \x01(\rH\x03R\fmaxDutyCycle\x88\x01\x01B\x05\n" +
	"\x03_drB\x11\n" +
	"\x0f_tx_power_indexB\v\n" +
	"\t_nb_transB\x11\n" +
	"\x0f_max_duty_cycle\"\xaa\x01\n" +
	"\x19DeviceConfigStoreListItem\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\tR\x06devEui\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8f\x01\n" +
	"\x13DeviceUplinkChannel\x12\x1c\n" +
	"\tfrequency\x18\x01 \x01(\rR\tfrequency\x12\x1d\n" +
	"\n" +
	"data_rates\x18\x02 \x03(\rR\tdataRates\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12!\n" +
	"\fuser_defined\x18\x05 \x01(\bR\vuserDefined\"~\n" +
	"\x1bSetDeviceConfigStoreRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\tR\x06devEui\x12F\n" +
	"\x13device_config_store\x18\x02 \x01(\v2\x16.api.DeviceConfigStoreR\x11deviceConfigStore\"6\n" +
	"\x1bGetDeviceConfigStoreRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\tR\x06devEui\"\xdc\x01\n" +
	"\x1cGetDeviceConfigStoreResponse\x12F\n" +
	"\x13device_config_store\x18\x01 \x01(\v2\x16.api.DeviceConfigStoreR\x11deviceConfigStore\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"9\n" +
	"\x1eDeleteDeviceConfigStoreRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\tR\x06devEui\"t\n" +
	"\x1dListDeviceConfigStoresRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12%\n" +
	"\x0eapplication_id\x18\x03 \x01(\tR\rapplicationId\"y\n" +
	"\x1eListDeviceConfigStoresResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\rR\n" +
	"totalCount\x126\n" +
	"\x06result\x18\x02 \x03(\v2\x1e.api.DeviceConfigStoreListItemR\x06result\":\n" +
	"\x1fGetDeviceConfigAlignmentRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\tR\x06devEui\"\xd4\x02\n" +
	" GetDeviceConfigAlignmentResponse\x12H\n" +
	"\x1eenabled_uplink_channel_indices\x18\x01 \x01(\bH\x00R\x1benabledUplinkChannelIndices\x88\x01\x01\x12\x13\n" +
	"\x02dr\x18\x02 \x01(\bH\x01R\x02dr\x88\x01\x01\x12)\n" +
	"\x0etx_power_index\x18\x03 \x01(\bH\x02R\ftxPowerIndex\x88\x01\x01\x12\x1e\n" +
	"\bnb_trans\x18\x04 \x01(\bH\x03R\anbTrans\x88\x01\x01\x12)\n" +
	"\x0emax_duty_cycle\x18\x05 \x01(\bH\x04R\fmaxDutyCycle\x88\x01\x01B!\n" +
	"\x1f_enabled_uplink_channel_indicesB\x05\n" +
	"\x03_drB\x11\n" +
	"\x0f_tx_power_indexB\v\n" +
	"\t_nb_transB\x11\n" +
	"\x0f_max_duty_cycle\"8\n" +
	"\x1dGetDeviceCurrentParamsRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\tR\x06devEui\"\xbd\x02\n" +
	"\x1eGetDeviceCurrentParamsResponse\x12M\n" +
	"\bchannels\x18\x01 \x03(\v21.api.GetDeviceCurrentParamsResponse.ChannelsEntryR\bchannels\x12\x0e\n" +
	"\x02dr\x18\x02 \x01(\rR\x02dr\x12$\n" +
	"\x0etx_power_index\x18\x03 \x01(\rR\ftxPowerIndex\x12\x19\n" +
	"\bnb_trans\x18\x04 \x01(\rR\anbTrans\x12$\n" +
	"\x0emax_duty_cycle\x18\x05 \x01(\rR\fmaxDutyCycle\x1aU\n" +
	"\rChannelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.api.DeviceUplinkChannelR\x05value:\x028\x012\xb4\x06\n" +
	"\x18DeviceConfigStoreService\x12o\n" +
	"\x03Set\x12 .api.SetDeviceConfigStoreRequest\x1a\x16.google.protobuf.Empty\".\x82\xd3\xe4\x93\x02(:\x01*\x1a#/api/device_config_stores/{dev_eui}\x12w\n" +
	"\x03Get\x12 .api.GetDeviceConfigStoreRequest\x1a!.api.GetDeviceConfigStoreResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/device_config_stores/{dev_eui}\x12r\n" +
	"\x06Delete\x12#.api.DeleteDeviceConfigStoreRequest\x1a\x16.google.protobuf.Empty\"+\x82\xd3\xe4\x93\x02%*#/api/device_config_stores/{dev_eui}\x12r\n" +
	"\x04List\x12\".api.ListDeviceConfigStoresRequest\x1a#.api.ListDeviceConfigStoresResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/device_config_stores\x12\x9e\x01\n" +
	"\x18GetDeviceConfigAlignment\x12$.api.GetDeviceConfigAlignmentRequest\x1a%.api.GetDeviceConfigAlignmentResponse\"5\x82\xd3\xe4\x93\x02/\x12-/api/device_config_stores/{dev_eui}/alignment\x12\xa4\x01\n" +
	"\x16GetDeviceCurrentParams\x12\".api.GetDeviceCurrentParamsRequest\x1a#.api.GetDeviceCurrentParamsResponse\"A\x82\xd3\xe4\x93\x02;\x129/api/device_config_stores/{dev_eui}/device_current_configB\x9c\x01\n" +
	"\x11io.chirpstack.apiB\x16DeviceConfigStoreProtoP\x01Z.github.com/chirpstack/chirpstack/api/go/v4/api\xaa\x02\x0eChirpstack.Api\xca\x02\x0eChirpstack\\Api\xe2\x02\x1aGPBMetadata\\Chirpstack\\Apib\x06proto3"

var (
	file_api_device_config_store_proto_rawDescOnce sync.Once
	file_api_device_config_store_proto_rawDescData []byte
)

func file_api_device_config_store_proto_rawDescGZIP() []byte {
	file_api_device_config_store_proto_rawDescOnce.Do(func() {
		file_api_device_config_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_device_config_store_proto_rawDesc), len(file_api_device_config_store_proto_rawDesc)))
	})
	return file_api_device_config_store_proto_rawDescData
}

var file_api_device_config_store_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_device_config_store_proto_goTypes = []any{
	(*DeviceConfigStore)(nil),                // 0: api.DeviceConfigStore
	(*DeviceConfigStoreListItem)(nil),        // 1: api.DeviceConfigStoreListItem
	(*DeviceUplinkChannel)(nil),              // 2: api.DeviceUplinkChannel
	(*SetDeviceConfigStoreRequest)(nil),      // 3: api.SetDeviceConfigStoreRequest
	(*GetDeviceConfigStoreRequest)(nil),      // 4: api.GetDeviceConfigStoreRequest
	(*GetDeviceConfigStoreResponse)(nil),     // 5: api.GetDeviceConfigStoreResponse
	(*DeleteDeviceConfigStoreRequest)(nil),   // 6: api.DeleteDeviceConfigStoreRequest
	(*ListDeviceConfigStoresRequest)(nil),    // 7: api.ListDeviceConfigStoresRequest
	(*ListDeviceConfigStoresResponse)(nil),   // 8: api.ListDeviceConfigStoresResponse
	(*GetDeviceConfigAlignmentRequest)(nil),  // 9: api.GetDeviceConfigAlignmentRequest
	(*GetDeviceConfigAlignmentResponse)(nil), // 10: api.GetDeviceConfigAlignmentResponse
	(*GetDeviceCurrentParamsRequest)(nil),    // 11: api.GetDeviceCurrentParamsRequest
	(*GetDeviceCurrentParamsResponse)(nil),   // 12: api.GetDeviceCurrentParamsResponse
	nil,                                      // 13: api.GetDeviceCurrentParamsResponse.ChannelsEntry
	(*timestamppb.Timestamp)(nil),            // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 15: google.protobuf.Empty
}
var file_api_device_config_store_proto_depIdxs = []int32{
	14, // 0: api.DeviceConfigStoreListItem.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: api.DeviceConfigStoreListItem.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: api.SetDeviceConfigStoreRequest.device_config_store:type_name -> api.DeviceConfigStore
	0,  // 3: api.GetDeviceConfigStoreResponse.device_config_store:type_name -> api.DeviceConfigStore
	14, // 4: api.GetDeviceConfigStoreResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 5: api.GetDeviceConfigStoreResponse.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 6: api.ListDeviceConfigStoresResponse.result:type_name -> api.DeviceConfigStoreListItem
	13, // 7: api.GetDeviceCurrentParamsResponse.channels:type_name -> api.GetDeviceCurrentParamsResponse.ChannelsEntry
	2,  // 8: api.GetDeviceCurrentParamsResponse.ChannelsEntry.value:type_name -> api.DeviceUplinkChannel
	3,  // 9: api.DeviceConfigStoreService.Set:input_type -> api.SetDeviceConfigStoreRequest
	4,  // 10: api.DeviceConfigStoreService.Get:input_type -> api.GetDeviceConfigStoreRequest
	6,  // 11: api.DeviceConfigStoreService.Delete:input_type -> api.DeleteDeviceConfigStoreRequest
	7,  // 12: api.DeviceConfigStoreService.List:input_type -> api.ListDeviceConfigStoresRequest
	9,  // 13: api.DeviceConfigStoreService.GetDeviceConfigAlignment:input_type -> api.GetDeviceConfigAlignmentRequest
	11, // 14: api.DeviceConfigStoreService.GetDeviceCurrentParams:input_type -> api.GetDeviceCurrentParamsRequest
	15, // 15: api.DeviceConfigStoreService.Set:output_type -> google.protobuf.Empty
	5,  // 16: api.DeviceConfigStoreService.Get:output_type -> api.GetDeviceConfigStoreResponse
	15, // 17: api.DeviceConfigStoreService.Delete:output_type -> google.protobuf.Empty
	8,  // 18: api.DeviceConfigStoreService.List:output_type -> api.ListDeviceConfigStoresResponse
	10, // 19: api.DeviceConfigStoreService.GetDeviceConfigAlignment:output_type -> api.GetDeviceConfigAlignmentResponse
	12, // 20: api.DeviceConfigStoreService.GetDeviceCurrentParams:output_type -> api.GetDeviceCurrentParamsResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_device_config_store_proto_init() }
func file_api_device_config_store_proto_init() {
	if File_api_device_config_store_proto != nil {
		return
	}
	file_api_device_config_store_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_device_config_store_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_device_config_store_proto_rawDesc), len(file_api_device_config_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_device_config_store_proto_goTypes,
		DependencyIndexes: file_api_device_config_store_proto_depIdxs,
		MessageInfos:      file_api_device_config_store_proto_msgTypes,
	}.Build()
	File_api_device_config_store_proto = out.File
	file_api_device_config_store_proto_goTypes = nil
	file_api_device_config_store_proto_depIdxs = nil
}
