// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/device_config_store.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChMaskConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enabled uplink channels.
	EnabledUplinkChannelIndices []uint32 `protobuf:"varint,1,rep,packed,name=enabled_uplink_channel_indices,json=enabledUplinkChannelIndices,proto3" json:"enabled_uplink_channel_indices,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ChMaskConfig) Reset() {
	*x = ChMaskConfig{}
	mi := &file_api_device_config_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChMaskConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChMaskConfig) ProtoMessage() {}

func (x *ChMaskConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChMaskConfig.ProtoReflect.Descriptor instead.
func (*ChMaskConfig) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{0}
}

func (x *ChMaskConfig) GetEnabledUplinkChannelIndices() []uint32 {
	if x != nil {
		return x.EnabledUplinkChannelIndices
	}
	return nil
}

type DeviceConfigStore struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (EUI64).
	DevEui string `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// ChMask configuration object.
	ChmaskConfig  *ChMaskConfig `protobuf:"bytes,2,opt,name=chmask_config,json=chmaskConfig,proto3" json:"chmask_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceConfigStore) Reset() {
	*x = DeviceConfigStore{}
	mi := &file_api_device_config_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConfigStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConfigStore) ProtoMessage() {}

func (x *DeviceConfigStore) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceConfigStore.ProtoReflect.Descriptor instead.
func (*DeviceConfigStore) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceConfigStore) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

func (x *DeviceConfigStore) GetChmaskConfig() *ChMaskConfig {
	if x != nil {
		return x.ChmaskConfig
	}
	return nil
}

type ConfigStoreAlignment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alignment of the ChMask configuration
	ChmaskConfig  bool `protobuf:"varint,1,opt,name=chmask_config,json=chmaskConfig,proto3" json:"chmask_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigStoreAlignment) Reset() {
	*x = ConfigStoreAlignment{}
	mi := &file_api_device_config_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigStoreAlignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigStoreAlignment) ProtoMessage() {}

func (x *ConfigStoreAlignment) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigStoreAlignment.ProtoReflect.Descriptor instead.
func (*ConfigStoreAlignment) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigStoreAlignment) GetChmaskConfig() bool {
	if x != nil {
		return x.ChmaskConfig
	}
	return false
}

type DeviceConfigStoreListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (EUI64).
	DevEui string `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceConfigStoreListItem) Reset() {
	*x = DeviceConfigStoreListItem{}
	mi := &file_api_device_config_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConfigStoreListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConfigStoreListItem) ProtoMessage() {}

func (x *DeviceConfigStoreListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceConfigStoreListItem.ProtoReflect.Descriptor instead.
func (*DeviceConfigStoreListItem) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceConfigStoreListItem) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

func (x *DeviceConfigStoreListItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DeviceConfigStoreListItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeviceUplinkChannel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Frequency Hz.
	Frequency uint32 `protobuf:"varint,1,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// Min. data-rate.
	MinDr uint32 `protobuf:"varint,2,opt,name=min_dr,json=minDr,proto3" json:"min_dr,omitempty"`
	// Max. data-rate.
	MaxDr uint32 `protobuf:"varint,3,opt,name=max_dr,json=maxDr,proto3" json:"max_dr,omitempty"`
	// Whether this channel is enabled on the device.
	Enabled bool `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Whether this channel is not among regional defaults.
	UserDefined   bool `protobuf:"varint,5,opt,name=user_defined,json=userDefined,proto3" json:"user_defined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceUplinkChannel) Reset() {
	*x = DeviceUplinkChannel{}
	mi := &file_api_device_config_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceUplinkChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceUplinkChannel) ProtoMessage() {}

func (x *DeviceUplinkChannel) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceUplinkChannel.ProtoReflect.Descriptor instead.
func (*DeviceUplinkChannel) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceUplinkChannel) GetFrequency() uint32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *DeviceUplinkChannel) GetMinDr() uint32 {
	if x != nil {
		return x.MinDr
	}
	return 0
}

func (x *DeviceUplinkChannel) GetMaxDr() uint32 {
	if x != nil {
		return x.MaxDr
	}
	return 0
}

func (x *DeviceUplinkChannel) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DeviceUplinkChannel) GetUserDefined() bool {
	if x != nil {
		return x.UserDefined
	}
	return false
}

type SetDeviceConfigStoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Object to set.
	DeviceConfigStore *DeviceConfigStore `protobuf:"bytes,1,opt,name=device_config_store,json=deviceConfigStore,proto3" json:"device_config_store,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetDeviceConfigStoreRequest) Reset() {
	*x = SetDeviceConfigStoreRequest{}
	mi := &file_api_device_config_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceConfigStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceConfigStoreRequest) ProtoMessage() {}

func (x *SetDeviceConfigStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceConfigStoreRequest.ProtoReflect.Descriptor instead.
func (*SetDeviceConfigStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{5}
}

func (x *SetDeviceConfigStoreRequest) GetDeviceConfigStore() *DeviceConfigStore {
	if x != nil {
		return x.DeviceConfigStore
	}
	return nil
}

type GetDeviceConfigStoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (EUI64).
	DevEui        string `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceConfigStoreRequest) Reset() {
	*x = GetDeviceConfigStoreRequest{}
	mi := &file_api_device_config_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceConfigStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceConfigStoreRequest) ProtoMessage() {}

func (x *GetDeviceConfigStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceConfigStoreRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceConfigStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{6}
}

func (x *GetDeviceConfigStoreRequest) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

type GetDeviceConfigStoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device configuration store object.
	DeviceConfigStore *DeviceConfigStore `protobuf:"bytes,1,opt,name=device_config_store,json=deviceConfigStore,proto3" json:"device_config_store,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceConfigStoreResponse) Reset() {
	*x = GetDeviceConfigStoreResponse{}
	mi := &file_api_device_config_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceConfigStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceConfigStoreResponse) ProtoMessage() {}

func (x *GetDeviceConfigStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceConfigStoreResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceConfigStoreResponse) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeviceConfigStoreResponse) GetDeviceConfigStore() *DeviceConfigStore {
	if x != nil {
		return x.DeviceConfigStore
	}
	return nil
}

func (x *GetDeviceConfigStoreResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetDeviceConfigStoreResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeleteDeviceConfigStoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (EUI64).
	DevEui        string `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceConfigStoreRequest) Reset() {
	*x = DeleteDeviceConfigStoreRequest{}
	mi := &file_api_device_config_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceConfigStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceConfigStoreRequest) ProtoMessage() {}

func (x *DeleteDeviceConfigStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceConfigStoreRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeviceConfigStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDeviceConfigStoreRequest) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

type ListDeviceConfigStoresRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Max number of chmasks to return in the result-set.
	// If not set, it will be treated as 0, and the response will only return the total_count.
	Limit uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset uint32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Application ID (UUID) to filter devices on.
	ApplicationId string `protobuf:"bytes,3,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceConfigStoresRequest) Reset() {
	*x = ListDeviceConfigStoresRequest{}
	mi := &file_api_device_config_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceConfigStoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceConfigStoresRequest) ProtoMessage() {}

func (x *ListDeviceConfigStoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceConfigStoresRequest.ProtoReflect.Descriptor instead.
func (*ListDeviceConfigStoresRequest) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{9}
}

func (x *ListDeviceConfigStoresRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDeviceConfigStoresRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListDeviceConfigStoresRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type ListDeviceConfigStoresResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of configuration stores.
	TotalCount uint32 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Result-set.
	Result        []*DeviceConfigStoreListItem `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceConfigStoresResponse) Reset() {
	*x = ListDeviceConfigStoresResponse{}
	mi := &file_api_device_config_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceConfigStoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceConfigStoresResponse) ProtoMessage() {}

func (x *ListDeviceConfigStoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceConfigStoresResponse.ProtoReflect.Descriptor instead.
func (*ListDeviceConfigStoresResponse) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{10}
}

func (x *ListDeviceConfigStoresResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListDeviceConfigStoresResponse) GetResult() []*DeviceConfigStoreListItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetConfigStoreAlignmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (EUI64).
	DevEui        string `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigStoreAlignmentRequest) Reset() {
	*x = GetConfigStoreAlignmentRequest{}
	mi := &file_api_device_config_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigStoreAlignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigStoreAlignmentRequest) ProtoMessage() {}

func (x *GetConfigStoreAlignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigStoreAlignmentRequest.ProtoReflect.Descriptor instead.
func (*GetConfigStoreAlignmentRequest) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{11}
}

func (x *GetConfigStoreAlignmentRequest) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

type GetConfigStoreAlignmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device alignment status with the stored configuration.
	Alignment     *ConfigStoreAlignment `protobuf:"bytes,1,opt,name=alignment,proto3" json:"alignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigStoreAlignmentResponse) Reset() {
	*x = GetConfigStoreAlignmentResponse{}
	mi := &file_api_device_config_store_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigStoreAlignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigStoreAlignmentResponse) ProtoMessage() {}

func (x *GetConfigStoreAlignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigStoreAlignmentResponse.ProtoReflect.Descriptor instead.
func (*GetConfigStoreAlignmentResponse) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{12}
}

func (x *GetConfigStoreAlignmentResponse) GetAlignment() *ConfigStoreAlignment {
	if x != nil {
		return x.Alignment
	}
	return nil
}

type GetAvailableChannelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (EUI64).
	DevEui        string `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableChannelsRequest) Reset() {
	*x = GetAvailableChannelsRequest{}
	mi := &file_api_device_config_store_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableChannelsRequest) ProtoMessage() {}

func (x *GetAvailableChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableChannelsRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableChannelsRequest) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{13}
}

func (x *GetAvailableChannelsRequest) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

type GetAvailableChannelsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Available uplink channels.
	Channels      map[uint32]*DeviceUplinkChannel `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableChannelsResponse) Reset() {
	*x = GetAvailableChannelsResponse{}
	mi := &file_api_device_config_store_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableChannelsResponse) ProtoMessage() {}

func (x *GetAvailableChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_config_store_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableChannelsResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableChannelsResponse) Descriptor() ([]byte, []int) {
	return file_api_device_config_store_proto_rawDescGZIP(), []int{14}
}

func (x *GetAvailableChannelsResponse) GetChannels() map[uint32]*DeviceUplinkChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

var File_api_device_config_store_proto protoreflect.FileDescriptor

const file_api_device_config_store_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/device_config_store.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"S\n" +
	"\fChMaskConfig\x12C\n" +
	"\x1eenabled_uplink_channel_indices\x18\x01 \x03(\rR\x1benabledUplinkChannelIndices\"d\n" +
	"\x11DeviceConfigStore\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\tR\x06devEui\x126\n" +
	"\rchmask_config\x18\x02 \x01(\v2\x11.api.ChMaskConfigR\fchmaskConfig\";\n" +
	"\x14ConfigStoreAlignment\x12#\n" +
	"\rchmask_config\x18\x01 \x01(\bR\fchmaskConfig\"\xaa\x01\n" +
	"\x19DeviceConfigStoreListItem\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\tR\x06devEui\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9e\x01\n" +
	"\x13DeviceUplinkChannel\x12\x1c\n" +
	"\tfrequency\x18\x01 \x01(\rR\tfrequency\x12\x15\n" +
	"\x06min_dr\x18\x02 \x01(\rR\x05minDr\x12\x15\n" +
	"\x06max_dr\x18\x03 \x01(\rR\x05maxDr\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12!\n" +
	"\fuser_defined\x18\x05 \x01(\bR\vuserDefined\"e\n" +
	"\x1bSetDeviceConfigStoreRequest\x12F\n" +
	"\x13device_config_store\x18\x01 \x01(\v2\x16.api.DeviceConfigStoreR\x11deviceConfigStore\"6\n" +
	"\x1bGetDeviceConfigStoreRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\tR\x06devEui\"\xdc\x01\n" +
	"\x1cGetDeviceConfigStoreResponse\x12F\n" +
	"\x13device_config_store\x18\x01 \x01(\v2\x16.api.DeviceConfigStoreR\x11deviceConfigStore\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"9\n" +
	"\x1eDeleteDeviceConfigStoreRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\tR\x06devEui\"t\n" +
	"\x1dListDeviceConfigStoresRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12%\n" +
	"\x0eapplication_id\x18\x03 \x01(\tR\rapplicationId\"y\n" +
	"\x1eListDeviceConfigStoresResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\rR\n" +
	"totalCount\x126\n" +
	"\x06result\x18\x02 \x03(\v2\x1e.api.DeviceConfigStoreListItemR\x06result\"9\n" +
	"\x1eGetConfigStoreAlignmentRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\tR\x06devEui\"Z\n" +
	"\x1fGetConfigStoreAlignmentResponse\x127\n" +
	"\talignment\x18\x01 \x01(\v2\x19.api.ConfigStoreAlignmentR\talignment\"6\n" +
	"\x1bGetAvailableChannelsRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\tR\x06devEui\"\xc2\x01\n" +
	"\x1cGetAvailableChannelsResponse\x12K\n" +
	"\bchannels\x18\x01 \x03(\v2/.api.GetAvailableChannelsResponse.ChannelsEntryR\bchannels\x1aU\n" +
	"\rChannelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.api.DeviceUplinkChannelR\x05value:\x028\x012\xc7\x06\n" +
	"\x18DeviceConfigStoreService\x12\x83\x01\n" +
	"\x03Set\x12 .api.SetDeviceConfigStoreRequest\x1a\x16.google.protobuf.Empty\"B\x82\xd3\xe4\x93\x02<:\x01*\x1a7/api/device_config_stores/{device_config_store.dev_eui}\x12w\n" +
	"\x03Get\x12 .api.GetDeviceConfigStoreRequest\x1a!.api.GetDeviceConfigStoreResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/device_config_stores/{dev_eui}\x12r\n" +
	"\x06Delete\x12#.api.DeleteDeviceConfigStoreRequest\x1a\x16.google.protobuf.Empty\"+\x82\xd3\xe4\x93\x02%*#/api/device_config_stores/{dev_eui}\x12r\n" +
	"\x04List\x12\".api.ListDeviceConfigStoresRequest\x1a#.api.ListDeviceConfigStoresResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/device_config_stores\x12\x9b\x01\n" +
	"\x17GetConfigStoreAlignment\x12#.api.GetConfigStoreAlignmentRequest\x1a$.api.GetConfigStoreAlignmentResponse\"5\x82\xd3\xe4\x93\x02/\x12-/api/device_config_stores/{dev_eui}/alignment\x12\xa5\x01\n" +
	"\x1aGetAvailableUplinkChannels\x12 .api.GetAvailableChannelsRequest\x1a!.api.GetAvailableChannelsResponse\"B\x82\xd3\xe4\x93\x02<\x12:/api/device_config_stores/{dev_eui}/usable_uplink_channelsB\x9c\x01\n" +
	"\x11io.chirpstack.apiB\x16DeviceConfigStoreProtoP\x01Z.github.com/chirpstack/chirpstack/api/go/v4/api\xaa\x02\x0eChirpstack.Api\xca\x02\x0eChirpstack\\Api\xe2\x02\x1aGPBMetadata\\Chirpstack\\Apib\x06proto3"

var (
	file_api_device_config_store_proto_rawDescOnce sync.Once
	file_api_device_config_store_proto_rawDescData []byte
)

func file_api_device_config_store_proto_rawDescGZIP() []byte {
	file_api_device_config_store_proto_rawDescOnce.Do(func() {
		file_api_device_config_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_device_config_store_proto_rawDesc), len(file_api_device_config_store_proto_rawDesc)))
	})
	return file_api_device_config_store_proto_rawDescData
}

var file_api_device_config_store_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_device_config_store_proto_goTypes = []any{
	(*ChMaskConfig)(nil),                    // 0: api.ChMaskConfig
	(*DeviceConfigStore)(nil),               // 1: api.DeviceConfigStore
	(*ConfigStoreAlignment)(nil),            // 2: api.ConfigStoreAlignment
	(*DeviceConfigStoreListItem)(nil),       // 3: api.DeviceConfigStoreListItem
	(*DeviceUplinkChannel)(nil),             // 4: api.DeviceUplinkChannel
	(*SetDeviceConfigStoreRequest)(nil),     // 5: api.SetDeviceConfigStoreRequest
	(*GetDeviceConfigStoreRequest)(nil),     // 6: api.GetDeviceConfigStoreRequest
	(*GetDeviceConfigStoreResponse)(nil),    // 7: api.GetDeviceConfigStoreResponse
	(*DeleteDeviceConfigStoreRequest)(nil),  // 8: api.DeleteDeviceConfigStoreRequest
	(*ListDeviceConfigStoresRequest)(nil),   // 9: api.ListDeviceConfigStoresRequest
	(*ListDeviceConfigStoresResponse)(nil),  // 10: api.ListDeviceConfigStoresResponse
	(*GetConfigStoreAlignmentRequest)(nil),  // 11: api.GetConfigStoreAlignmentRequest
	(*GetConfigStoreAlignmentResponse)(nil), // 12: api.GetConfigStoreAlignmentResponse
	(*GetAvailableChannelsRequest)(nil),     // 13: api.GetAvailableChannelsRequest
	(*GetAvailableChannelsResponse)(nil),    // 14: api.GetAvailableChannelsResponse
	nil,                                     // 15: api.GetAvailableChannelsResponse.ChannelsEntry
	(*timestamppb.Timestamp)(nil),           // 16: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 17: google.protobuf.Empty
}
var file_api_device_config_store_proto_depIdxs = []int32{
	0,  // 0: api.DeviceConfigStore.chmask_config:type_name -> api.ChMaskConfig
	16, // 1: api.DeviceConfigStoreListItem.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: api.DeviceConfigStoreListItem.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: api.SetDeviceConfigStoreRequest.device_config_store:type_name -> api.DeviceConfigStore
	1,  // 4: api.GetDeviceConfigStoreResponse.device_config_store:type_name -> api.DeviceConfigStore
	16, // 5: api.GetDeviceConfigStoreResponse.created_at:type_name -> google.protobuf.Timestamp
	16, // 6: api.GetDeviceConfigStoreResponse.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 7: api.ListDeviceConfigStoresResponse.result:type_name -> api.DeviceConfigStoreListItem
	2,  // 8: api.GetConfigStoreAlignmentResponse.alignment:type_name -> api.ConfigStoreAlignment
	15, // 9: api.GetAvailableChannelsResponse.channels:type_name -> api.GetAvailableChannelsResponse.ChannelsEntry
	4,  // 10: api.GetAvailableChannelsResponse.ChannelsEntry.value:type_name -> api.DeviceUplinkChannel
	5,  // 11: api.DeviceConfigStoreService.Set:input_type -> api.SetDeviceConfigStoreRequest
	6,  // 12: api.DeviceConfigStoreService.Get:input_type -> api.GetDeviceConfigStoreRequest
	8,  // 13: api.DeviceConfigStoreService.Delete:input_type -> api.DeleteDeviceConfigStoreRequest
	9,  // 14: api.DeviceConfigStoreService.List:input_type -> api.ListDeviceConfigStoresRequest
	11, // 15: api.DeviceConfigStoreService.GetConfigStoreAlignment:input_type -> api.GetConfigStoreAlignmentRequest
	13, // 16: api.DeviceConfigStoreService.GetAvailableUplinkChannels:input_type -> api.GetAvailableChannelsRequest
	17, // 17: api.DeviceConfigStoreService.Set:output_type -> google.protobuf.Empty
	7,  // 18: api.DeviceConfigStoreService.Get:output_type -> api.GetDeviceConfigStoreResponse
	17, // 19: api.DeviceConfigStoreService.Delete:output_type -> google.protobuf.Empty
	10, // 20: api.DeviceConfigStoreService.List:output_type -> api.ListDeviceConfigStoresResponse
	12, // 21: api.DeviceConfigStoreService.GetConfigStoreAlignment:output_type -> api.GetConfigStoreAlignmentResponse
	14, // 22: api.DeviceConfigStoreService.GetAvailableUplinkChannels:output_type -> api.GetAvailableChannelsResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_device_config_store_proto_init() }
func file_api_device_config_store_proto_init() {
	if File_api_device_config_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_device_config_store_proto_rawDesc), len(file_api_device_config_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_device_config_store_proto_goTypes,
		DependencyIndexes: file_api_device_config_store_proto_depIdxs,
		MessageInfos:      file_api_device_config_store_proto_msgTypes,
	}.Build()
	File_api_device_config_store_proto = out.File
	file_api_device_config_store_proto_goTypes = nil
	file_api_device_config_store_proto_depIdxs = nil
}
